### ISSUE TITLE
LockLogin Hook

### ISSUE THREAD

**Issue by CroaBeast** [Insprill/Custom-Join-Messages#10]
**Description of feature/improvement request:**
LockLogin PreJoinEvent
---
### Detailed explanation of what it should do, when and in what situation: ###
Add LockLogin Pre Join Event, to not send any first join / join messages when the player is not registered or logged.

**Comment by Insprill** [comment]
While support is possible, I've decided I will not add it. The developers are very hostile towards using their API, and all of their code is under a highly restrictive license that defeats most of the point of it being open source in the first place. The license terms are also not very clear in regards to how it applies when using the API, and I will not go through the trouble of getting explicit permission, which requires giving them personal information. I'd be open to adding support in the future if the developers add a normal API, or at the very least, use a normal license that's compatible with the GPLv3 that CustomJoinMessages is licensed under, such as the GPLv3, LGPLv3, Apache 2.0, and many others. If you'd like to see that change, it'll be up to you to talk to them as I will not.
