### ISSUE TITLE
EssentialsX Jail Support

### ISSUE THREAD

**Issue by ClickyMCSMP** [Insprill/Custom-Join-Messages#14]
**Description of feature/improvement request:**
I think it'd be a huge addition for this plugin to support EssentialsX Jails. So what it'd do is if a user is jailed, it cancels out the users join and leave message completely in order to prevent annoying spam by the offenders.

---
### Detailed explanation of what it should do, when and in what situation: ###
Situation:
A player is `/jailed` using the essentialsx jail system.
While usually they cannot talk and or enter commands, they can still leave and join which if the user has a join / leave message, it's shown in chat. So they could just troll and be annoying my constantly joining and leaving. This support would basically void the users join / leave message, maybe even an option to disable it for X amount of time + an option to disable it completely until they're no longer jailed.

**Comment by ClickyMCSMP** [comment]
> Can you add/remove permissions if someone is jailed? I feel that would be a much more flexible solution

 I feel that too- but as far as im aware, you cannot do such a thing with the essentialsx.

**Comment by Insprill** [comment]
Added for CJM 17
