### ISSUE TITLE
Display names don't work in join messages?

### ISSUE THREAD

**Issue by ClickyMCSMP** [Insprill/Custom-Join-Messages#15]
**Description of issue:**
I have tried two displayname placedholders, %player_displayname%, and the built in one, %displayname%, and both seem to not display the displayname, but rather display the color infront of the placeholder. This seems to ONLY happen on the join message - the leave message displays the display name perfectly.
![image](https://user-images.githubusercontent.com/92657250/142013206-316cafa5-c80e-44d2-a804-3342b3b0deb0.png)

**CONFIG SECTION**
`      5:
        Permission: cjm.ethereal
        Messages:
          1:
            - '&8(&c&l✘&8) &eOur &x&d&d&d&f&1&b&lE&x&e&2&d&9&2&6&lT&x&e&7&d&3&3&1&lH&x&e&c&c&d&3&c&lE&x&f&0&c&7&4&6&lR&x&f&5&c&1&5&1&lE&x&f&a&b&b&5&c&lA&x&f&f&b&5&6&7&lL&e donator, &x&a&e&b&7&0&d%player_displayname%&e, has left!'`
            
`      5:
        Permission: cjm.ethereal
        Messages:
          1:
            - '&8(&a&l✔&8) &eOur &x&d&d&d&f&1&b&lE&x&e&2&d&9&2&6&lT&x&e&7&d&3&3&1&lH&x&e&c&c&d&3&c&lE&x&f&0&c&7&4&6&lR&x&f&5&c&1&5&1&lE&x&f&a&b&b&5&c&lA&x&f&f&b&5&6&7&lL&e donator, &x&a&e&b&7&0&d%player_displayname%&e, has joined!'`

**Output of "/cjm version"!**
![image](https://user-images.githubusercontent.com/92657250/142013501-061879ad-b1e2-4046-85f1-5dfea7aa914c.png)

**Comment by Insprill** [comment]
What plugin is managing the display name? Try adding some delay to the message, it's probably not being loaded in time.

**Comment by ClickyMCSMP** [comment]
> What plugin is managing the display name? Try adding some delay to the message, it's probably not being loaded in time.

I am using EssentialsX displayname, along with the built in one inside the plugin that is listed inside of the top of the config. Could you explain how to add a delay..?

**Comment by ClickyMCSMP** [comment]
I think it's an issue with CJM... I've tested other players/ways to display the name using essentialsx display_name placeholder, and it worked just fine... something just doesn't work in cjm, please fix this?

**Comment by Insprill** [comment]
You can see how to add a delay on the wiki. Can almost guarantee that'll fix it.

**Comment by ClickyMCSMP** [comment]
Is it possible to make the delay almost not noticeable?

**Comment by Insprill** [comment]
Just set it to the lowest that still allows for the names to reliably load.
