### ISSUE TITLE
Preview Join/Leave messages without having to leave and rejoin the server

### ISSUE THREAD

**Issue by Vyladence** [Insprill/Custom-Join-Messages#17]
something like `/cjm preview join` and `cjm preview leave` to view the join and leave messages without having to join or leave the server. As it currently stands, there's no way to see the leave message without an alt account. 

I feel that it should also be private, so it'll only send the message to the person executing the command rather than to the whole server.

**Comment by Insprill** [comment]
Added for CJM 17
