### ISSUE TITLE
Make the indicators emissive.

### ISSUE THREAD

**Issue by Drebledore** [Insprill/Custom-Join-Messages#18]
**Description of feature/improvement request:**

---
Make the text glow or emissive, you cannot see the text in the dark especially with shaders. Idk if it's possible with plugins but it would be an awesome improvement.

**Comment by Insprill** [comment]
Was this meant to go on Damage Indicator's page? Assuming it was, that's not possible.

**Comment by Drebledore** [comment]
I see, thank you.
