### ISSUE TITLE
Allow users to create their own world groups for join messages to be sent in

### ISSUE THREAD

**Issue by Vyladence** [Insprill/Custom-Join-Messages#30]
In most plugins chat-related, you can define world groups for chat messages to be synced between. I'd like to see that functionality in CJM as well.

Currently, the plugin automatically detects the worlds to have the join messages for. So the functionality to send messages to separate worlds is there, I just think it could be implemented better. 

I'm thinking, in the worlds file, have something like this:
```
Group1:
    - World
    - World2
Group2:
    - World3
```
or something simple like that.

**Comment by Insprill** [comment]
Implemented in 6c829d5
