### ISSUE TITLE
Delay option for messages 

### ISSUE THREAD

**Issue by 1ntent1on** [Insprill/Custom-Join-Messages#34]
**Description of feature/improvement request:**
Simple delay option for messages.
---
### Detailed explanation of what it should do, when and in what situation: ###
Possibility to delay all types of messages, lets say that you want to send title to player 3s after he joins. 

Example:
```
          Title: "Title"
          SubTitle: ""
          Fade-In: 50
          Stay: 60
          Fade-Out: 20
          Delay: 60
```

**Comment by Insprill** [comment]
Implemented in 516c2ac
