### ISSUE TITLE
Add support for multiple formatters

### ISSUE THREAD

**Issue by Insprill** [Insprill/custom-join-messages#37]
**Description of feature/improvement request:**
Add a config option to change which text formatter is used since no one can agree on one, and there are still people not using Paper. 

Perhaps we could add Adventure support via BungeeCord components to maintain support with Spigot servers, which would also allow us to use MiniMessage.

Example config:
```yaml
# Which formatter should be used to format text. You can choose from the following:
# - MineDown (https://github.com/Phoenix616/MineDown)
# - MiniMessage (https://docs.adventure.kyori.net/minimessage/format.html#minimessage-format)
# - Legacy (Legacy color codes. e.g. &a, &l, {#000000}, &#000000)
formatter: MineDown
```

**Comment by iRobSch** [comment]
Good to know for others: until this is implemented, placeholders such as the prefix from LuckPerms will be unusable until this is implemented. If you want to use those, use "Custom-Join-Messages-17.0.0-SNAPSHOT+rev.463f1e8.jar".

**Comment by Insprill** [comment]
b633c83efe269968b1654459c6353c7e2d52ba1f is the last revision with the old formatting
