### ISSUE TITLE
World based name placeholders

### ISSUE THREAD

**Issue by ImmortalLeaf101** [Insprill/custom-join-messages#38]
### Describe the Feature

When world-based messages are used, there should be placeholders with the names of the worlds the player travels to and from.

### Provide Reasoning

So servers can send messages showing the world a player came from and went to.
Ex: "Player traveled from Lobby to Survival!"

### Checklist

- [X] I have searched the [issue tracker](https://github.com/Insprill/custom-join-messages/issues) to ensure there are no similar feature requests
- [X] I have read the wiki to ensure this isn't already possible
- [ ] I ticked all of the boxes without actually reading them

**Comment by Insprill** [comment]
Upon further consideration, this feature won't be implemented. In some cases, the current system isn't built to handle this, mainly with the configuration of world-based messages but also with handling some state of which worlds the player has been to. Perhaps sometime in the future, we can integrate more customizable world-based features, but as of now, it's not feasible.
