### ISSUE TITLE
Delay before send the messages

### ISSUE THREAD

**Issue by cupang-afk** [Insprill/custom-join-messages#39]
### Describe the Feature

i would like to add delay before sending the messages for player join

for example, the plugin send the join message after 2 second something like that

### Provide Reasoning

i'd like to wait any player related class to be loaded before sending the join message 

i had placeholderapi checking for the message using [this expansion](https://github.com/Kqliber/Expansion-ChangeOutput)
and the value that I checked in also had to wait for it to load first

### Checklist

- [X] I have searched the [issue tracker](https://github.com/Insprill/custom-join-messages/issues) to ensure there are no similar feature requests
- [X] I have read the wiki to ensure this isn't already possible
- [X] I ticked all of the boxes without actually reading them

**Comment by Insprill** [comment]
This is already a feature; It just needed to be documented somewhere. I've since updated the documentation. You can find the docs around this feature [here](https://cjm.insprill.net/en/latest/message-types/messages.html#global-parameters).
