### ISSUE TITLE
Improved incorrect name display

### ISSUE THREAD

**Issue by Pantera07** [Insprill/Custom-Join-Messages#40]
### Describe the Feature

`______komq_____`
This name gets underscored and the name gets weirdly changed.

![1](https://user-images.githubusercontent.com/89838384/226410412-39c301fb-dc62-42fd-b241-5929c0775f15.png)

### Provide Reasoning

The player's name must be displayed as is.

### Checklist

- [X] I have searched the [issue tracker](https://github.com/Insprill/custom-join-messages/issues) to ensure there are no similar feature requests
- [X] I have read the wiki to ensure this isn't already possible
- [ ] I ticked all of the boxes without actually reading them

**Comment by Insprill** [comment]
That's a pretty uncommon username, and this has to do with what formatter you're using. Minedown is the default, where `__text__` is the syntax to underline text. You can disable the underline formatter for usernames by doing `...[%displayname%](format=!underlined)`. Check out the [formatting page of the wiki](https://cjm.insprill.net/en/latest/writing-messages/formatting.html) for more information.

**Comment by Insprill** [comment]
CJM is using MineDown 1.7.1-SNAPSHOT which is the latest version. Either way, this would be an issue with MineDown, not CJM.
