### ISSUE TITLE
Disable data logging

### ISSUE THREAD

**Issue by Pantera07** [Insprill/custom-join-messages#41]
### Describe the Feature

1. Disable `worlds.json` logging when `World-Based-Messages` is disabled.
2. I don't know what `toggles.json` is for.

### Provide Reasoning

Disabling toggles.json and worlds.json logging should give you some performance benefit.

### Checklist

- [X] I have searched the [issue tracker](https://github.com/Insprill/custom-join-messages/issues) to ensure there are no similar feature requests
- [X] I have read the wiki to ensure this isn't already possible
- [ ] I ticked all of the boxes without actually reading them

**Comment by Insprill** [comment]
The `worlds.json` file doesn't get updated when world-based messages are disabled. Does it get created? Yes. But no data is ever written to, or read from it.

The `toggles.json` file is for storing what players have enabled/disabled messages. Run `/cjm help` for more information.

Changing either of these wouldn't give a performance benefit. Before wanting to change things for performance, see if there's actually a need for it. Unless your server has noticeable lag spikes and you've used spark to narrow it down to my plugin writing to a file, you don't have an issue.
