### ISSUE TITLE
see if it is possible to use minimessage and legacy together like invero does.

### ISSUE THREAD

**Issue by Zarkness** [Insprill/custom-join-messages#44]
### Describe the Feature

Hi, I don't know if it would be possible to set that you can use both legacy and minimessage colors at the same time.

I was looking and this plugin is a menu plugin https://github.com/Arasple/Invero and has so that in the menus you can use both colors, to use it in the name of items, lore, menu name, I imagine that could be done for chat, the only thing as I'm not dev I do not know well how it does, but I imagine that you to know programming and especially kotlin, which is the language in which this plugin is made, you can see well how it does it

### Provide Reasoning

comfort so you don't have to be putting in the config the option you want so you put directly the message in the config.

### Checklist

- [X] I have searched the [issue tracker](https://github.com/Insprill/custom-join-messages/issues) to ensure there are no similar feature requests
- [X] I have read the wiki to ensure this isn't already possible
- [X] I ticked all of the boxes without actually reading them

**Comment by Zarkness** [comment]
@Insprill ?

**Comment by Insprill** [comment]
It's not possible

**Comment by Zarkness** [comment]
hello @Insprill  i saw that this plugin has support to use both minimessage and legacy here is the part of the code i saw where it uses support for both, would it be possible to add something like this to use both?

https://github.com/kyngs/LegacyMessage/blob/master/LegacyMessage/src/main/java/xyz/kyngs/utils/legacymessage/LegacyMessage.java

https://github.com/kyngs/LibreLogin/blob/master/Plugin/src/main/java/xyz/kyngs/librelogin/common/config/HoconMessages.java

**Comment by Zarkness** [comment]
hi, @Insprill on this, could you add something like this plugin has to be able to use both minimessage and legacy colors at the same time?

https://github.com/kyngs/LibreLogin/blob/master/Plugin/src/main/java/xyz/kyngs/librelogin/common/config/HoconMessages.java

https://github.com/kyngs/LegacyMessage/blob/master/LegacyMessage/src/main/java/xyz/kyngs/utils/legacymessage/LegacyMessage.java

**Comment by Insprill** [comment]
I'll look into it again, no promises but I'll see what I can do

**Comment by Zarkness** [comment]
ok, even though it makes me a little weird because the only thing I ask from the legacy section is the colors and formats, I do not ask you to add also the legacy json and that with a replace as the plugin has said before, it arrives
