### ISSUE TITLE
Quit message don't send

### ISSUE THREAD

**Issue by TheAIguy-dev** [Insprill/custom-join-messages#45]
### Server Version

Paper 1.18.2 build 388

### CJM Version

17.2.4

### Describe the Bug

When the player quits the server, quit message does not show up.

### Expected Behavior

Quit message shows up.

### Steps to Reproduce

Step 1: install version 17.2.4 on your server
Step 2: load the plugin
Step 3: Quit message does not display!

### Server Logs

https://mclo.gs/n9SbTP7

### Additional Information

I just installed the plugin without changing absolutely anything, other than the chat messages themselves.
I have tested everything with the default configuration and the issue was still present.

### Checklist

- [X] I am running the latest version of the plugin
- [X] I have read the wiki to ensure it's not a configuration issue
- [ ] I ticked all of the boxes without actually reading them

**Comment by TheAIguy-dev** [comment]
Any info yet?

**Comment by Insprill** [comment]
Sorry about the late response. I've tried to reproduce this but couldn't. Can you remove all other plugins, see if the issue persists, then if not, slowly add them back until it happens again?

**Comment by TheAIguy-dev** [comment]
Steps to reproduce:
1) Get cjm
2) Get AuthMe
3) Restart server
Boom, not working.

**Comment by Insprill** [comment]
Thank you for the additional information! I'll check it out shortly.

**Comment by Insprill** [comment]
Fixed in 17.3.0.

**Comment by TheAIguy-dev** [comment]
Thank you!
