### ISSUE TITLE
Add support for JPremium

### ISSUE THREAD

**Issue by mario414x** [Insprill/custom-join-messages#46]
### Describe the Feature

Hello! This is similar to the already existing support for Authme. The messages would be sended after the authentification. This is the plugin: https://www.spigotmc.org/resources/%E2%96%A0-jpremium-%E2%96%A0-authorization-plugin-%E2%96%A0-automatic-login-premium-%E2%96%A0.27766/

### Provide Reasoning

This would help users which are already using JPremium. Here is the API: https://jakubson.github.io/JPremiumCleared/

### Checklist

- [X] I have searched the [issue tracker](https://github.com/Insprill/custom-join-messages/issues) to ensure there are no similar feature requests
- [X] I have read the wiki to ensure this isn't already possible
- [ ] I ticked all of the boxes without actually reading them

**Comment by Insprill** [comment]
JPremium only works on proxies and doesn't appear to send any data to the backend servers, so adding support isn't possible.
