### ISSUE TITLE
VelocityVanish shows quit message on join when vanished

### ISSUE THREAD

**Issue by alexander4342** [Insprill/custom-join-messages#47]
### Describe the Feature

add velocityvanish support

### Provide Reasoning

add velocityvanish support

### Checklist

- [X] I have searched the [issue tracker](https://github.com/Insprill/custom-join-messages/issues) to ensure there are no similar feature requests
- [X] I have read the wiki to ensure this isn't already possible
- [ ] I ticked all of the boxes without actually reading them

**Comment by Insprill** [comment]
CJM already supports VelocityVanish?
