### ISSUE TITLE
Could not pass event PlayerJoinEvent to CustomJoinMessages v17.3.1

### ISSUE THREAD

**Issue by Ryoyo2** [Insprill/custom-join-messages#52]
### Server Version

Purpur version git-Purpur-2132 (MC: 1.20.4)

### CJM Version

17.3.1

### Describe the Bug

Upon joining the server myself (this doesn't seem to happen with every player), an error pops up. It seems that this error doesn't affect functioniality, however the console spam is a bit annoying. Error is in the attached log. If further information is required, please reply to this thread.

### Expected Behavior

No error.

### Steps to Reproduce

Step 1: Join the server.

### Server Logs

https://mclo.gs/5bZumkm

### Checklist

- [X] I am running the latest version of the plugin
- [X] I have read the wiki to ensure it's not a configuration issue
- [ ] I ticked all of the boxes without actually reading them

**Comment by Insprill** [comment]
It looks like a config error. Can you send your chat message config?

**Comment by Ryoyo2** [comment]
That is entirely possible. I took some values/placeholders i had in the plugin from back in 2021 after putting my server back online a couple days ago. I believe I only modified the chat.yml. All other yml's are set to false.

https://mclo.gs/hqMjT9n

**Comment by Insprill** [comment]
You have a syntax error on line 40. There needs to be a space between the hyphen and the quotes. So instead of 
```yaml
Messages:
  1:
    -""
```
it needs to be
```yaml
Messages:
  1:
    - ""
```
You can remove the entire `Join` section if you don't need it.

**Comment by Ryoyo2** [comment]
Thank you for the quick help! This fixed it. Apologies for not seeing it myself.

There is one last thing that I actually originally wanted to bring to your attention beforehand because I saw it in the reviews section if I am not mistaken. It is not a huge deal but the console spam is again just mildly annoying. If you know any remedy there, that would be great as well.

https://mclo.gs/dTogZlY

**Comment by Insprill** [comment]
Please open a separate issue for that and I'll get to it soon - it's most likely a simple fix so it shouldn't take long.
