### ISSUE TITLE
add papi placeholder

### ISSUE THREAD

**Issue by Zarkness** [Insprill/custom-join-messages#53]
### Describe the Feature

add the possibility to use the placeholder %uniquejoins% in other places not only in the plugin messages but also in any other place such as the scoreboard

### Provide Reasoning

possibility to use it on scoreboards or tabs or holograms and show how many players connected in total

### Checklist

- [X] I have searched the [issue tracker](https://github.com/Insprill/custom-join-messages/issues) to ensure there are no similar feature requests
- [X] I have read the wiki to ensure this isn't already possible
- [X] I ticked all of the boxes without actually reading them

**Comment by Zarkness** [comment]
hi, insprill on this issue #44 that i opened some time ago, could you add something like this plugin has to be able to use both minimessage and legacy colors at the same time?

https://github.com/kyngs/LibreLogin/blob/master/Plugin/src/main/java/xyz/kyngs/librelogin/common/config/HoconMessages.java

https://github.com/kyngs/LegacyMessage/blob/master/LegacyMessage/src/main/java/xyz/kyngs/utils/legacymessage/LegacyMessage.java

**Comment by Insprill** [comment]
You can get all CJM placeholders from PAPI extensions. `%server_unique_joins%` from the `Server` extension (`/papi ecloud download Server`) does what CJM's `%uniquejoins%` does.

Please don't bring up topics from other issues that are unrelated. If you have more to add to a closed issue, you can still comment there, and I'll reopen it if deemed necessary.
