### ISSUE TITLE
Can't read players locale

### ISSUE THREAD

**Issue by Ryoyo2** [Insprill/custom-join-messages#54]
### Server Version

git-Paper-405 (MC: 1.20.4)

### CJM Version

17.3.1

### Describe the Bug

Upon joining, an error occurs. It does not affect functionality, it's just some spam. It does not happen with every player. I believe it might even only be the first player after starting the server, but can't confirm as of now due to the server still being in testing.

### Expected Behavior

No error.

### Steps to Reproduce

1. Join the server.

### Server Logs

https://mclo.gs/Cuh0CJZ

### Checklist

- [X] I am running the latest version of the plugin
- [X] I have read the wiki to ensure it's not a configuration issue
- [ ] I ticked all of the boxes without actually reading them

**Comment by xzrvr** [comment]
exact same issue with me, latest spigot.jar, CJM 17.3.1

**Comment by Insprill** [comment]
Fixed in 17.3.2. Apologies for the delay in fixing this.
