### ISSUE TITLE
Add support for AdvancedVanish

### ISSUE THREAD

**Issue by MrCipherUa** [Insprill/custom-join-messages#56]
### Server Version

git-Purpur-2035

### CJM Version

17.4.1

### Describe the Bug

When I stay in vanish while using AdvancedVanish and rejoin the server a message gets sent that I joined tha game.

### Expected Behavior

It is expected that join message doesn't show up when I join while in a vanish state.

### Steps to Reproduce

Step 1: Use the latest Custom Join Messages version
Step 2: Use AdvancedVanish https://www.spigotmc.org/resources/advancedvanish.86036/
Step 3: Join the server

### Server Logs

https://mclo.gs/VHYOose

### Checklist

- [X] I am running the latest version of the plugin
- [X] I have read the wiki to ensure it's not a configuration issue
- [ ] I ticked all of the boxes without actually reading them

**Comment by Insprill** [comment]
I've added support for Advanced Vanish on the dev branch. Once it's done building, you can download the build [here](https://github.com/Insprill/custom-join-messages/actions/runs/8758605959). Please try it out and let me know how it works!

**Comment by MrCipherUa** [comment]
I tried the newest build, advanced vanish works well now, but there is a critical bug now, basically when you leave the game it doesn't send the "player left the game" message in chat. I think my config is alright and I tested it on two different servers, could you try to reproduce it and fix it?

**Comment by Insprill** [comment]
I wasn't able to reproduce what you described. However, I did find another major bug with the implementation, which I've now fixed. You can download the updated build [here](https://github.com/Insprill/custom-join-messages/actions/runs/8765506797); please let me know if it also fixed your problem.

**Comment by MrCipherUa** [comment]
I fixed the problem. There are no more bugs for me anymore, thanks for adding Advanced Vanish
