### ISSUE TITLE
sayanvanish 

### ISSUE THREAD

**Issue by t4ba** [Insprill/custom-join-messages#57]
### Describe the Feature

please add sayanvanish plugin support

### Provide Reasoning

with this we can use custom messages with sound for sayanvanish plugin 

### Checklist

- [X] I have searched the [issue tracker](https://github.com/Insprill/custom-join-messages/issues) to ensure there are no similar feature requests
- [X] I have read the wiki to ensure this isn't already possible
- [ ] I ticked all of the boxes without actually reading them

**Comment by Insprill** [comment]
I've added support for SayanVanish in the latest dev builds. You can download it from [Hanger](https://hangar.papermc.io/Insprill/Custom-Join-Messages/versions/17.5.0+rev.6129334) or from [GitHub Actions](https://github.com/Insprill/custom-join-messages/actions/runs/9509884485/artifacts/1600565030). Please give it a try and let me know if it works :)

**Comment by Insprill** [comment]
Added in 17.6.0.
