### ISSUE TITLE
Rank join messages not working

### ISSUE THREAD

**Issue by gandra123** [Insprill/custom-join-messages#59]
### Server Version

Paper 1.20.6

### CJM Version

17.6.0

### Describe the Bug

Join message for players with the permission do not show, they show just the default message.

### Expected Behavior

Every rank should have its own join message.

### Steps to Reproduce

Create a join message in public chat for example:

  Join:
    1:
      Permission: cjm.svip
      Messages:
        1:
          - "<dark_gray>[</dark_gray><green>+</green><dark_gray>] <hover:show_text:'%name%\n%server_time_hh:mm:ss%'>%name%</hover></dark_gray>"

Give rank silvervip permission cjm.svip

### Server Logs

https://mclo.gs/6rpQVTd

### Checklist

- [X] I am running the latest version of the plugin
- [X] I have read the wiki to ensure it's not a configuration issue
- [ ] I ticked all of the boxes without actually reading them

**Comment by Insprill** [comment]
Please zip up CJM's config folder and send it so I can try to reproduce the issue.

**Comment by gandra123** [comment]
It was a issue at my end, everything works fine now.
