### ISSUE TITLE
Add an option to play any sound when someone joins/leaves

### ISSUE THREAD

**Issue by simoneedotexe** [Insprill/Custom-Join-Messages#7]
**Description of feature/improvement request:**
Add an option to play any sound to people with permissions when someone joins/leaves.

---
### Detailed explanation of what it should do, when and in what situation: ###
 I intend to use this to be alerted whenever a new person joins so I can welcome them. Make the permission to hear the sound from the join/leave event customizable like other permissions.

**Comment by Insprill** [comment]
Added for CJM 17
