### ISSUE TITLE
PremiumVanish x CJM bug

### ISSUE THREAD

**Issue by MuffinDotExE** [Insprill/Custom-Join-Messages#9]
**Description of issue:**
if i go into vanish its doing its job by saying that i quit but when i leave the server its saying that i left again and other people can see it to 
![2021 06 04_1035](https://user-images.githubusercontent.com/82248707/120731551-29ee4200-c4e4-11eb-99dc-8934489a25ff.png)

i tried everything but its just not working

**Output of "/cjm version" (yes, everything)** 
CJM: 16.0.2
Server: git-Paper-634 (MC: 1.16.5)
PAPI Version: 2.10.9
Java: 11.0.11
OS: Linux

**Comment by Insprill** [comment]
Why was this closed?

**Comment by MuffinDotExE** [comment]
we just deleted every config so they are regenerating and its working now
